### ISSUE TITLE
Appveyor 帳號被 ban 了

### ISSUE THREAD

**Issue by watain666** [tasi788/PTTAutoSign#2]
如旨

Appveyor 官方說違反使用條例，

他們的服務不可以用於機器人，請問有解決方法嗎？

詳見我去 Appveyor ci repo 提問的 issue

[There was an error while trying to complete the current operation. Please contact AppVeyor support. #3695](https://github.com/appveyor/ci/issues/3695#issuecomment-889466521)

**Comment by ptntp** [comment]
請問您是用 github 帳號登入嗎？謝謝

**Comment by watain666** [comment]
> 請問您是用 github 帳號登入嗎？謝謝

嗯 我是用 Github 帳號登入的沒錯

登入完還可以設定，後來來看一下發現執行失敗了，

就去 Appveyor 看一下發現帳號沒辦法做任何操作

**Comment by ptntp** [comment]
了解，等待今日其他大大的狀況回報好了

**Comment by tasi788** [comment]
我今天可能有點忙，需要晚一點才能處理 😢

**Comment by watain666** [comment]
TDC 大你忙你的，我 Appveyor 是新註冊的，
被 Ban 對我沒影響，所以不急
Side project 本來就是有空時才處理的 👍

**Comment by ptntp** [comment]
> > 請問您是用 github 帳號登入嗎？謝謝
> 
> 嗯 我是用 Github 帳號登入的沒錯
> 
> 登入完還可以設定，後來看一下 Action 的 Log 發現執行失敗了，
> 
> 就去 Appveyor 看發現帳號沒辦法做任何操作，都會彈
> 
> `There was an error while trying to complete the current operation. Please contact AppVeyor support.`
> 
> 字串的紅色 Alert

咦我出現這則警告是用一般註冊的帳號遇到的

**Comment by ptntp** [comment]
回報，appveyor 用 github 登入一樣遇到[警告](https://share.getcloudapp.com/xQu6PGZ8)！

**Comment by tasi788** [comment]
已找到其他解法，稍晚或等我睡醒就會改教學

**Comment by tasi788** [comment]
請參閱更新文件。

**Comment by watain666** [comment]
剛點 Layerci 進去就被導到 webapp 原來是 rebranded 了
[layerci.com has rebranded to webapp.io](https://webapp.io/blog/layerci-has-rebranded-to-webapp-io/)

**Comment by ptntp** [comment]
原來不是只有我遇到(哭倒

**Comment by tasi788** [comment]
😩 
等他 rebrand 完成好了

**Comment by ptntp** [comment]
@watain666 我剛剛有成功了，再試試看

**Comment by watain666** [comment]
> @watain666 我剛剛有成功了，再試試看

我這也沒問題了 感謝告知🙏
